# Generated by Django 4.1.1 on 2023-03-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='indore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gmail', models.CharField(max_length=20)),
                ('passw', models.CharField(max_length=20)),
                ('mobile', models.IntegerField(null=True)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
    ]
